runtime: python27
api_version: 1
threadsafe: yes
service: default

handlers:
- url: /tasks/process_queue
  script: process_queue.app
  login: admin

- url: /tasks/create_bq_table
  script: create_bq_table.app
  login: admin

- url: /collect
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
